Split votes page
datamade/chi-councilmatic pull request #328
Opened 2023-01-13 04:54 UTC by derekeder

Creates a new Split votes / dissenting votes page.

This page displays a list of legislation in a table where there are recorded 'no' votes. Currently, it is showing all legislation with any no votes and yields 700+ bills. Setting this threshold higher to 10 votes shows 100 bills, which is maybe more interesting and certainly loads the page faster.

<img width="1501" alt="Screen Shot 2023-01-12 at 10 53 27 PM" src="https://user-images.githubusercontent.com/919583/212240438-6f362308-a6bf-404d-a821-a599337060f1.png">

I found it useful to refer to one of Dick Simpson's reports on how to present this information. We may want to do some similar things: https://www.chicagotribune.com/opinion/commentary/ct-opinion-lightfoot-two-years-city-council-simpson-20210519-ogs6eifmuzghrevydirv63zwwe-story.html

2023-01-13 14:26 UTC, fgregg requested changes
Love where this is going. A few high level points.

1. I think it would make sense to segment by legislative session, i.e. term.
2. It would be good to add links for the vote to the detailed information about the vote on the bill page. We should be able to construct a slug with the name of the action and the date that can be used as anchor tags.
3. There can be multiple split votes on the same bill, i.e. in committee and then also on the final action. I think it would be great to show all those, maybe with a table in a table view. (there's seldom going to be more than three or so). 

For the future, it would be good to keep track of the mayor's floor leader so we can know whether the vote was going for or against the mayor.

@red-bin has been looking at some similar things.

2023-01-13 15:54 UTC, derekeder commented on chicago/views.py
> +                actions__vote__counts__value__gt=0, actions__vote__counts__option="no"
good call. i'll filter on just the full council

2023-01-13 21:44 UTC, derekeder commented
Notes on things to do:

- use django `url` for legislation links
- note who the mayor is for each legislative session
- remove 2007 legislation session (little/no data)

2023-01-13 22:39 UTC, derekeder commented on chicago/templates/council_members.html
> +  {% cache 86400 js_wrapper_compare 'js' %}
using the same cache wrapper on the council members map and compare page is causing an error

2023-01-13 22:46 UTC, derekeder commented
@fgregg ok this is ready for another look

- filtering on legislative session
- more efficient vote query
- adds nav link
- showing who the mayor is for each session
- removed 2007 from session list
- handling not found legislative session 404

Unrelated, adds a fix for the broken Aldermen map on production.

![Screen Shot 2023-01-13 at 4 45 55 PM](https://user-images.githubusercontent.com/919583/212432800-9c1b965a-3865-4bd6-b798-dc95ed7f6ab3.png)

2023-01-14 00:25 UTC, fgregg approved these changes

2023-01-14 02:37 UTC, merged