better event page: vimeo embed, event agenda
datamade/chi-councilmatic pull request #359
Opened 2023-09-01 21:33 UTC by derekeder

For events with Vimeo links, shows that as an embed at the top:

![Screen Shot 2023-09-01 at 4 28 35 PM](https://github.com/datamade/chi-councilmatic/assets/919583/eddf421e-8633-475e-9342-34bcb5be59f7)

Formats the agenda as a table with links to ordinances and sponsors:

![Screen Shot 2023-09-01 at 4 31 21 PM](https://github.com/datamade/chi-councilmatic/assets/919583/bf108f91-4241-405c-9476-eef0a82d68bd)

2023-09-01 21:34 UTC, derekeder commented on chicago/models.py
> +    def clean_agenda_items(self):
@fgregg I pulled this over from `django-councilmatic` and added a `prefetch_related` but I think I did it wrong. The page is very slow to load still

2023-09-01 21:34 UTC, derekeder commented on chicago/models.py
> +            vimeo_id = re.match(".*?([0-9]+)$", link).group(1)
assuming the links are all vimeo and that the ID is always the last part of it, which seems to be the case

2023-09-09 00:31 UTC, fgregg commented
optimized a lot of the queries here. probably fast enough now @derekeder

2023-09-09 00:32 UTC, fgregg requested changes

2023-09-09 00:32 UTC, fgregg commented on chicago/models.py
> +            print(link, vimeo_id)
remove this print statement.

2023-09-11 19:11 UTC, merged